/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.4.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package api;

import model.Dictionary;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2024-04-02T21:55:45.453890500+02:00[Europe/Warsaw]", comments = "Generator version: 7.4.0")
@Validated
@Tag(name = "dictionaries", description = "the dictionaries API")
public interface DictionariesApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * GET /dictionaries : List All Dictionaries
     * Gets a list of all &#x60;Dictionary&#x60; entities.
     *
     * @return Successful response - returns an array of &#x60;Dictionary&#x60; entities. (status code 200)
     */
    @Operation(
        operationId = "getDictionaries",
        summary = "List All Dictionaries",
        description = "Gets a list of all `Dictionary` entities.",
        responses = {
            @ApiResponse(responseCode = "200", description = "Successful response - returns an array of `Dictionary` entities.", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = Dictionary.class)))
            })
        },
        security = {
            @SecurityRequirement(name = "bearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/dictionaries",
        produces = { "application/json" }
    )
    
    default ResponseEntity<List<Dictionary>> getDictionaries(
        
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "[ { \"dataDate\" : \"2000-01-23T04:56:07.000+00:00\", \"values\" : [ { \"id\" : 6, \"label\" : \"label\", \"value\" : \"value\" }, { \"id\" : 6, \"label\" : \"label\", \"value\" : \"value\" } ], \"name\" : \"name\", \"id\" : 0, \"version\" : 6 }, { \"dataDate\" : \"2000-01-23T04:56:07.000+00:00\", \"values\" : [ { \"id\" : 6, \"label\" : \"label\", \"value\" : \"value\" }, { \"id\" : 6, \"label\" : \"label\", \"value\" : \"value\" } ], \"name\" : \"name\", \"id\" : 0, \"version\" : 6 } ]";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
